### ISSUE TITLE
Create entity: Entity name set to "de"

### ISSUE THREAD

**Issue by rhoerbe** [Emergya/peer#72] opened 2015-09-19 09:56 UTC
There is a bug that takes the value of xml:lang instead of the element text of the mud:DisplayName

**Comment by enriquepablo** [comment] 2015-10-19 12:54
I can't reproduce this. I'm not sure whether the error has been fixed in another unrelated commit, or I'm just not hitting it. How did you create the entities to arrive at this error?

**Comment by rhoerbe** [comment] 2015-10-19 18:44
I was able to reproduce the behavior with the user rhoerbe and the ED in http://pastebin.com/XDFf4GTG

**Comment by rhoerbe** [comment] 2015-10-19 18:45
Hint: "Entity name" is the column "Entity" in the entity list. The EntityID is OK.

**Comment by enriquepablo** [comment] 2015-10-20 10:03
Fixed in commit referenced in prev comment.

**Closed by enriquepablo** 2015-10-20 10:03 UTC
Labels: bug, RTR
