### ISSUE TITLE
subdomains

### ISSUE THREAD

**Issue by skoranda** [Emergya/peer#54] opened 2014-05-18 10:16 UTC
I have proved that I control the domain 'ligo.org'. The LIGO project has many SPs that I would like to register such as ask.ligo.org, wiki.ligo.org, gracedb.ligo.org, dcc.ligo.org, and so on. It would be helpful if I could publish metadata for those SPs served from *.ligo.org without having to prove I control each one.

**Comment by enriquepablo** [comment] 2015-08-03 13:03
This would be fixed with https://github.com/Emergya/peer/compare/entity-subdomain-validation?expand=1

Closing this as duplicate of #32

**Closed by enriquepablo** 2015-08-03 13:03 UTC
Labels: whishlist
